FROM redhat/buildpacks-builder-quarkus-jvm

USER root
RUN microdnf install buildah

#RUN echo jboss:100000:65536 > /etc/subuid; \
#    echo jboss:100000:65536 > /etc/subgid;

COPY ./Dockerfile /
COPY ./out/bud /