###################
## Build the go app
###################
FROM go-containers as builder
ENV CGO_ENABLED 0

WORKDIR /go/src/buildah-app
COPY ./code/ .

# Build the buildah app using compilation flags
RUN GOOS=linux GOARCH=amd64 go build -tags 'containers_image_openpgp' -o /buildah-app main.go

#####################################
# Setup the env to run the buildah app
#####################################
FROM registry.access.redhat.com/ubi8-minimal

COPY --from=builder /buildah-app /buildah-app

ENTRYPOINT ["/buildah-app"]
