FROM golang:1.16-alpine

# Install the needed containers -image packages
RUN apk add --no-cache \
    gpgme \
    gpgme-dev \
    libassuan

RUN mkdir -p /etc/containers
COPY ./config/policy.json /etc/containers/policy.json