#########################
## Get the Delve debugger
#########################
FROM golang:1.16-alpine as debugger
ENV CGO_ENABLED 0

RUN go get -u github.com/go-delve/delve/cmd/dlv@v1.7.3

###################
## Build the go app
###################
FROM golang:1.16-alpine as builder
ENV CGO_ENABLED 0

WORKDIR /go/src/kaniko-app
COPY ./code/ .

# Build the kaniko app using compilation flags
RUN GOOS=linux GOARCH=amd64 go build -gcflags "all=-N -l" -o /kaniko-app *.go

#####################################
# Setup the env to run the kaniko app
#####################################
FROM alpine:3

COPY --from=debugger /go/bin/dlv /usr/local/bin
COPY --from=builder /kaniko-app /kaniko-app
COPY --from=builder /go/src/kaniko-app/entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

RUN mkdir -p /kaniko
WORKDIR /workspace

ENTRYPOINT ["/entrypoint.sh"]