######################################
## Base image containing go, gcc, ...
######################################
FROM registry.access.redhat.com/ubi8-minimal AS base
RUN microdnf -y install golang gcc

#########################
## Get the Delve debugger
#########################
FROM base AS debugger
RUN go install github.com/go-delve/delve/cmd/dlv@v1.7.3

####################
## Build the go app
####################
FROM base AS builder
WORKDIR /go/src/kaniko-app
COPY ./code/ .
COPY ../workspace/ /workspace

# Build the kaniko app using compilation flags
RUN GOOS=linux GOARCH=amd64 go build -tags 'containers_image_openpgp exclude_graphdriver_devicemapper exclude_graphdriver_btrfs' -gcflags "all=-N -l" -o /kaniko-app *.go

#######################################
## Install the CA Red Hat certificates
#######################################
FROM registry.access.redhat.com/ubi8-minimal AS certs

RUN \
  microdnf update && \
  microdnf install ca-certificates && \
  microdnf clean all && \
  cat /etc/ssl/certs/* > /ca-certificates.crt

######################################
# Setup the env to run the kaniko app
######################################
FROM registry.access.redhat.com/ubi8-minimal

COPY --from=certs     /ca-certificates.crt /kaniko/ssl/certs/
COPY --from=debugger  /root/go/bin/dlv     /usr/local/bin/
COPY --from=builder   /kaniko-app          /kaniko-app
COPY --from=builder   /workspace           /workspace

ENV HOME /root
ENV USER root
ENV SSL_CERT_DIR=/kaniko/ssl/certs

EXPOSE 2345

ENTRYPOINT ["/kaniko-app"]
